config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts do
    resources :comments 
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end  
  end
  root "posts#index"
  get '/about', to: 'pages#about'
  get '/terms', to: 'pages#terms'
  get 'u/:id', to: 'users#show', as: :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	before_save :update_slug
	belongs_to :user
	has_many :comments, dependent: :destroy
	acts_as_votable
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
	def update_slug
		self.slug=title.parameterize
	end
	def to_param
		slug
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :update_slug
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { profile: "300x300>", thumb: "40x40>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    def update_slug
	  self.slug="@"+username.parameterize
	end
	
	def to_param
		slug
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:fullname, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :fullname, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find_by_slug(params[:post_id])
		
		@comment = @post.comments.create(params[:comment].permit(:name, :body, :email))
		redirect_to post_path(@post)
		flash[:alert] = "Comment Successfully Created."
	end
	def destroy
		@post = Post.find_by_slug(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
		flash[:alert] = "Comment Successfully Deleted."
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
	end
	def terms
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show,:edit,:update,:destroy]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts=Post.all.order("created_at DESC")
        if params[:search]
            @posts = Post.where(["title LIKE ?","%#{params[:search]}%"])
        else
            @posts = Post.all.order('created_at DESC')
        end
    end
    def new
        @post = current_user.posts.build
    end
    def show
    end
    def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
			flash[:alert] = "Post Successfully Created."
		else
			render 'new'
		end
    end
    def edit
    end
    def update
		if @post.update(post_params)
			redirect_to @post
			flash[:alert] = "Post Successfully Updated."
		else
			render 'edit'
		end
    end
    def destroy
		@post.destroy
		redirect_to root_path
		flash[:alert] = "Post Successfully Deleted."
    end
    def upvote
        @post = Post.find_by_slug(params[:id])
        @post.upvote_by current_user
        redirect_to post_path
    end
    def downvote
        @post = Post.find_by_slug(params[:id])
        @post.downvote_by current_user
        redirect_to post_path
    end
    private
    def find_post
        @post = Post.find_by_slug(params[:id])
    end   
    def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find_by_slug(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/term_helper.rb
module TermHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago | Comment ID:<%= comment.id %></p>
	</div>
	<% if comment.email == current_user.email %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.hidden_field :email, :value => current_user.email %>
	<%= f.hidden_field :name, :value => current_user.fullname %>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag "https://apis.google.com/js/plusone.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>
		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://facebook.com/waleed.zahid.73">Facebook</a></li>
			<li><a href="https://twitter.com/waleedzahid_">Twitter</a></li>
			<li><a href="https://github.com/waleedzahid106a">Github</a></li>
			<li><a href="mailto:waleed.zahid654@gmail.com">Email</a></li>
			<li><a href="/terms">Terms and Conditions</a></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% elsif current_page?(terms_path) %>
				<p>Terms and Conditions</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>
			<% if user_signed_in? %>
				<div class="buttons">
					<%= link_to "New Post", new_post_path, class: "button" %>
					<%= link_to "My Profile", users_path(current_user.slug), :class => "button" %>
					<%= link_to 'Log out', destroy_user_session_path, :method => :delete, :class => "button" %>
				</div>
			<% end %>
		</div>
		
		<% flash.each do |key, value| %>
  			<%= content_tag :div, value, class: "alert" %>
		<% end %>
		<%= yield %>
	</div>
</body>	
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "logo.svg" %>
	</div>
	<div id="content">
		<h1>Hey, I'm Waleed Zahid</h1>
		<p>Welcome to my WZBlog</p>
		<p>You can edit, delete, comment, like or dislike a post.</p>
	</div>
</div>

app/views/pages/terms.html.erb
<div id="page_wrapper">
    <h1>Terms and Conditions</h1>
    <div id="content">
        <p>If you Find any comment or post inappropriate</p>
        <p>Tell the admin by typing admindeletepostwithid for post</p>
        <p>Tell the admin by typing admindeletecommentwithid for comment</p>
        <p>Notice: Change id in their</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<br>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= post.created_at.strftime("%B %d, %Y") %> <i class="fa fa-user" aria-hidden="true"></i> <%= post.user.fullname %> <i class="fa fa-comment-o" aria-hidden="true"></i> <%= post.comments.count %> <i class="fa fa-heart-o" aria-hidden="true"></i> <%= post.get_upvotes.size %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1><%= image_tag current_user.avatar.url(:thumb) %>New Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	<p class="date">
		<i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(@post.created_at) %> Ago <i class="fa fa-user" aria-hidden="true"></i> <%= link_to @post.user.fullname, users_path(@post.user.slug)%>
		<% if user_signed_in? %>
		<%= link_to @post.get_upvotes.size, like_post_path(@post), method: :put, :class => "fa fa-thumbs-up" %>
		 <%= link_to @post.get_downvotes.size, dislike_post_path(@post), method: :put, :class => "fa fa-thumbs-down" %>
		<% end %>
		<% if @post.user == current_user %>
		 <%= link_to '', edit_post_path(@post), :class => "fa fa-pencil" %> 
		 <%= link_to '', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash" %>
	  <% end %>
	  | Post ID:<%= @post.id %>
	</p>
	<p class="body"><%= @post.body %></p>
	
		<div id="comments">
			<% if user_signed_in? %>
			<h2><%= @post.comments.count %> Comments</h2>
			<%= render @post.comments %>
			<h3>Add a Comment:</h3>
			<%= render "comments/form" %>
		<% else %>
			Please <%= link_to "Login", new_user_session_path %> to Comment
		<% end %>	
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div id="page_wrapper">
<%= image_tag @user.avatar.url(:profile) %>
<h1><%= @user.fullname %>(@<%= @user.username %>)</h1>
<h2>Email Address:<%= @user.email %></h2>
<h3>User ID:<%= @user.id %></h3>
<h3>Account Created at: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
<%= button_to "Edit User", edit_user_registration_path %>
<h1>Posts</h1>
<% if @user.posts.empty? %>
<h3>No Posts</h3>
<% else %>
<div class="post_wrapper">
<% @user.posts.each do |p| %>
<h3 class="title"><%= link_to p.title, post_path(p.slug) %></h3>
<p class="date"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= p.created_at.strftime("%B %d, %Y") %> <i class="fa fa-user" aria-hidden="true"></i> <%= p.user.fullname %> <i class="fa fa-comment-o" aria-hidden="true"></i> <%= p.comments.count %> <i class="fa fa-heart-o" aria-hidden="true"></i> <%= p.get_upvotes.size %></p>
<% end %>
</div>   
<% end %>   
</div>